##################################################
## MAKEFILE for Example Project
##################################################

CC=g++
CFLAGS=-g -ansi -pedantic -Wall

sdlexample: main.cpp
	$(CC) $(CFLAGS) -o sdlexample $^


.PHONY:
clean:
	rm -f sdlexample *.o *.g

